version: "3.9"


networks:
  default_net:
    name: default_net
    driver: bridge

volumes:
  database-store:
    driver: local

services:
  database:
    image: postgres:13
    container_name: database-api
    volumes:
      - ~/.docker-conf/postgres/data/:/var/lib/postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: tiago
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: authentication_db
    networks:
      - default_net

